import Head from 'next/head'
import { useAccount, useContractWrite, usePrepareContractWrite } from 'wagmi'
import { mainABI, mainAddress } from "../contract"

export default function Home() {

  // Global WAGMI hooks to access the connected wallet
  const { address, isConnected } = useAccount();

  // WAGMI hook for calling claim function
  // const buy = useContractWrite({
  //   ...config,
  //   onSuccess(data) {
  //     console.log("Successfully minted!", data);

  //     // After it the NFT has successfully been minted,
  //     // Create a receipt/transaction in Firebase
  //     createDocument();
  //   }
  // });

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="grid place-items-center justify-center">
            <div className="grid grid-cols-1 gap-6 content-center max-w-screen-lg">
              <div className="card w-96 bg-base-100 shadow-xl">
                <div className="card-body">
                  <h2 className="card-title">Card title!</h2>
                  <p>If a dog chews shoes whose shoes does he choose?</p>
                  <div className="card-actions justify-end">
                    <button className="btn btn-primary">Play</button>
                  </div>
                </div>
              </div>
            </div>
        </div>
      </main>
    </div>
  )
}
